---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - "/home/mau/multimedia/ext/tv_shows/:/tv_shows"
      - "/home/mau/multimedia/ext/movies/:/movies"
      - "/home/mau/multimedia/ext:/downloads"
      - "/home/mau/.config/qbittorrent/:/config"
      - "/home/mau/multimedia/torrents:/torrents"

    ports:
      - 8080:8080
      - 6882:6881
      - 6882:6881/udp
    restart: unless-stopped
