version: "3.7"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80 # For HTTP -> HTTPS redirects
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    labels:
      caddy.email: you@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/server/.config/caddy_config/:/config
      - /home/server/.config/caddy_data/:/data

  whoami:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.local
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

  adguardhome:
  image: adguard/adguardhome
  container_name: adguard
  networks:
    - caddy
  labels:
    caddy: adguard.local
    caddy.reverse_proxy: "{{upstreams 80}}"
    caddy.tls: "internal"
  ports:
    - 53:53/tcp
    - 53:53/udp
    - 3000:3000/tcp
  volumes:
    - /home/server/.config/adguard/:/config

networks:
  caddy:
    external: true
    driver: overlay
