version: "3.7"
services:
  ################################################
  ### NETWORKING
  ################################################

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80 # For HTTP -> HTTPS redirects
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    labels:
      caddy.email: you@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/server/.config/caddy_config/:/config
      - /home/server/.config/caddy_data/:/data

  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    labels:
      caddy: adguard.local.xyz
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 83:80/tcp
    volumes:
      - /home/server/.config/adguard/:/config

  ################################################
  ### MEDIA
  ################################################

  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    ports:
      - 8096:8096/tcp
    labels:
      caddy: emby.local.xyz
      caddy.reverse_proxy: "{{upstreams 8096}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/emby/:/config
      - /home/server/ext/tv/:/media/tv
      - /home/server/ext/movies/:/media/movies

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/prowlarr/:/config
    networks:
      - caddy
    labels:
      caddy: prowlarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 9696}}"
      caddy.tls: "internal"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/radarr/:/config
      - /home/server/ext/movies/:/media/movies
      - /home/server/ext/downloads_movies:/media/downloads_movies
    networks:
      - caddy
    labels:
      caddy: radarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 7878}}"
      caddy.tls: "internal"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/sonarr/:/config
      - /home/server/ext/tv/:/media/tv
      - /home/server/ext/downloads_tv:/media/downloads_tv
    networks:
      - caddy
    labels:
      caddy: sonarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 8989}}"
      caddy.tls: "internal"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/bazarr/:/config
      - /home/server/multimedia/ext/tv_shows/:/media/tv_shows
      - /home/server/multimedia/ext/movies/:/media/movies
    networks:
      - caddy
    labels:
      caddy: bazarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 6767}}"
      caddy.tls: "internal"
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    labels:
      caddy: ombi.local.xyz
      caddy.reverse_proxy: "{{upstreams 3579}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/ombi/:/config
    restart: unless-stopped

  ################################################
  ### DOWNLOADS
  ################################################

  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    networks:
      - caddy
    labels:
      caddy: torrent.local.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/qbittorrent/:/config
      - /home/server/ext/downloads_tv:/media/downloads_tv
      - /home/server/ext/downloads_movies:/media/downloads_movies
      - /home/server/ext/torrents:/media/torrents
    restart: unless-stopped

networks:
  caddy:
    external: true
    driver: overlay
