version: "3.7"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80 # For HTTP -> HTTPS redirects
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    labels:
      caddy.email: you@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/server/.config/caddy_config/:/config
      - /home/server/.config/caddy_data/:/data

  whoami:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.local.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

networks:
  caddy:
    external: true
    driver: overlay
