version: "3.7"
services:
  ################################################
  ### NETWORKING
  ################################################

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80 # For HTTP -> HTTPS redirects
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - AUTHP_ADMIN_USER=my-user
      - AUTHP_ADMIN_EMAIL=my@email.com
      - AUTHP_ADMIN_SECRET=auth-password
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    labels:
      caddy.email: my@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
      - caddy_access_log:/var/log/caddy

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/.config/fail2ban:/config
      - caddy_access_log:/var/log/caddy:ro
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    labels:
      caddy: adguard.local.xyz
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 83:80/tcp
    volumes:
      - adguard_conf:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work

  wireguard:
    container_name: wireguard
    environment:
      - WG_HOST=vpn.mydomain.com
      - PASSWORD=vpn-password
    image: weejewel/wg-easy
    networks:
      - caddy
    volumes:
      - ~/.config/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  ################################################
  ### MEDIA
  ################################################

  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    ports:
      - 8096:8096/tcp
    labels:
      caddy: emby.local.xyz
      caddy.reverse_proxy: "{{upstreams 8096}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/emby/:/config
      - /home/server/ext/tv/:/multimedia/tv
      - /home/server/ext/movies/:/multimedia/movies

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/prowlarr/:/config
    networks:
      - caddy
    labels:
      caddy: prowlarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 9696}}"
      caddy.tls: "internal"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/radarr/:/config
      - /home/server/ext/movies/:/multimedia/movies
      - /home/server/ext/downloads_movies:/multimedia/downloads_movies
    networks:
      - caddy
    labels:
      caddy: radarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 7878}}"
      caddy.tls: "internal"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/sonarr/:/config
      - /home/server/ext/tv/:/multimedia/tv
      - /home/server/ext/downloads_tv:/multimedia/downloads_tv
    networks:
      - caddy
    labels:
      caddy: sonarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 8989}}"
      caddy.tls: "internal"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/server/.config/bazarr/:/config
      - /home/server/multimedia/ext/tv_shows/:/multimedia/tv_shows
      - /home/server/multimedia/ext/movies/:/multimedia/movies
    networks:
      - caddy
    labels:
      caddy: bazarr.local.xyz
      caddy.reverse_proxy: "{{upstreams 6767}}"
      caddy.tls: "internal"
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      - caddy
    labels:
      caddy: ombi.local.xyz
      caddy.reverse_proxy: "{{upstreams 3579}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/ombi/:/config
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    networks:
      - caddy
    labels:
      caddy: fb.local.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
    volumes:
      - ~:/data
      - ~/.config/filebrowser:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: always

  ################################################
  ### DOWNLOADS
  ################################################

  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    networks:
      - caddy
    labels:
      caddy: torrent.local.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
    volumes:
      - /home/server/.config/qbittorrent/:/config
      - /home/server/ext/downloads_tv:/multimedia/downloads_tv
      - /home/server/ext/downloads_movies:/multimedia/downloads_movies
      - /home/server/ext/torrents:/multimedia/torrents
    restart: unless-stopped

  ################################################
  ### MONITORING
  ################################################

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    networks:
      - caddy
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    labels:
      caddy: hd.local.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
    volumes:
      - /run/udev:/run/udev:ro
      - ~/.config/scrutiny:/opt/scrutiny/config
      - ~/.config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"

  ################################################
  ### HOME
  ################################################

  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ~/.config/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

networks:
  caddy:
    external: true

volumes:
  caddy_data:
  caddy_config:
  caddy_access_log:
  adguard_work:
  adguard_conf:
