---
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2019"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
