global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blocky'

    static_configs:
    - targets: ['blocky:4000']

  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
    - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']
