{
 "title": "Caddy exporter",
 "description": "Dashboard set for Caddy proxy",
 "tags": [ "caddy" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values({__name__=~\"^caddy.*\",handler=~\".*\"},handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Geomap",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " {job=\"caddy\"} |= \"\" | json"
    },
    {
     "expr": "{job=\"caddy\"}  |= \"\" |  json  cf_remote_ip=`request.headers[\"Cf-Ipcountry\"][0]` "
    }
   ]
  },
  {
   "title": "Subdomains divide",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(count_over_time({job=\"caddy\"} |= \"\" | json [$__range])) by (request_host)",
     "legendFormat": "{{request_host}}"
    }
   ]
  },
  {
   "title": "Subdomains hits timeline",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": " sum(count_over_time({job=\"caddy\"} |= \"\" | json [1m])) by (request_host)",
     "legendFormat": "{{request_host}}"
    }
   ]
  },
  {
   "title": "IPs by number of requests",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(geoip_city_name) (count_over_time({job=\"caddy\"} |= `` | json [$__range]))",
     "legendFormat": "{{request_remote_ip}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"caddy\"} |= \"\" | json "
    }
   ]
  },
  {
   "title": "HTTP(S) errors total",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\"}[5m])))"
    }
   ]
  },
  {
   "title": "HTTP(S) requests total",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[5m])))"
    }
   ]
  }
 ]
}