---
server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /root/positions.yaml
clients:
  - url: "loki:3100/loki/api/v1/push"
scrape_configs:
  - job_name: caddy
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddy
          host: server
          __path__: /var/log/caddy/*
    pipeline_stages:
      - json:
          expressions:
            remote_ip: request.remote_ip
      - geoip:
          db: "/var/lib/geoip/GeoLite2-City.mmdb"
          source: remote_ip
          db_type: "city"
